# Generated by Django 4.2.5 on 2024-04-22 10:51

from django.db import migrations, models
import recipe_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=recipe_app.models.user_directory_path)),
            ],
        ),
    ]
